-- TIDES EVER FAVORABLE - MOVEMENT --
INSERT INTO Trait_FreePromotionUnitCombats
			(TraitType,		UnitCombatType,			PromotionType)
SELECT		'TRAIT_TIDES',	UnitCombatType,			'PROMOTION_TIDES'
FROM		Trait_FreePromotionUnitCombats WHERE TraitType = 'TRAIT_OCEAN_MOVEMENT';
--- THIS COPIES WHATEVER ENGLAND IS USING, AUTOMATICALLY FITTING VANILLA, GAK OR BNW ---

-- AI BEHAVIOUR INTRODUCED IN GAK --
INSERT INTO	Leader_MinorCivApproachBiases
			(LeaderType,	MinorCivApproachType,		Bias)
VALUES		(LEADER_LUNA,	MINOR_CIV_APPROACH_BULLY,	3);

INSERT INTO	Leader_Flavors
			(LeaderType,	FlavorType,			Flavor)
VALUES		(LEADER_LUNA,	FLAVOR_ESPIONAGE,	5),
			(LEADER_LUNA,	FLAVOR_USE_NUKE,	3),
			(LEADER_LUNA,	FLAVOR_ANTIAIR,		8),
			(LEADER_LUNA,	FLAVOR_AIR_CARRIER,	7);

--- INTRODUCED IN BNW ---
INSERT INTO	Leader_Flavors
			(LeaderType,	FlavorType,					Flavor)
VALUES		(LEADER_LUNA,	FLAVOR_ARCHAEOLOGY,			5),
			(LEADER_LUNA,	FLAVOR_I_LAND_TRADE_ROUTE,	6),
			(LEADER_LUNA,	FLAVOR_I_SEA_TRADE_ROUTE,	7),
			(LEADER_LUNA,	FLAVOR_I_TRADE_ORIGIN,		5),
			(LEADER_LUNA,	FLAVOR_I_TRADE_DESTINATION,	5),
			(LEADER_LUNA,	FLAVOR_AIRLIFT,				5);