CREATE TABLE ModData_ChangelingUnits( 'ID' INTEGER PRIMARY KEY AUTOINCREMENT,
'UnitType' TEXT NOT NULL, 'UnitArtDef' TEXT NOT NULL, 'UnitMemberArtDef' TEXT NOT NULL, NumMembers INT,
'Scale' FLOAT, 'Model' TEXT NOT NULL, MaterialTypeTag TEXT, MaterialTypeSoundOverrideTag TEXT);

INSERT INTO ModData_ChangelingUnits
	(UnitType,					UnitArtDef,						UnitMemberArtDef,				NumMembers, Scale,	Model, MaterialTypeTag, MaterialTypeSoundOverrideTag)
VALUES
	('UNIT_ANTI_AIRCRAFT_GUN',	'ART_DEF_UNIT_ANTI_AIRCRAFT_GUN', 'ART_DEF_UNIT_MEMBER_ANTIAIRCRAFTGUN',3, '0.50',	'AALing.fxsxml',		'CLOTH', 'FLESH'),
	('UNIT_ARCHER',				'ART_DEF_UNIT_ARCHER',			'ART_DEF_UNIT_MEMBER_ARCHER',			6, '0.14',	'ArcherLing.fxsxml',	'CLOTH', 'FLESH'),
	('UNIT_ARTIST',				'ART_DEF_UNIT_ARTIST',			'ART_DEF_UNIT_MEMBER_ARTIST',			1, '0.50',	'ArtistLing.fxsxml',	'CLOTH', 'FLESH'),
	('UNIT_ARTIST',				'ART_DEF_UNIT_GREAT_ARTIST',	'ART_DEF_UNIT_MEMBER_GREAT_ARTIST',		1, '0.50',	'ArtistLing.fxsxml',	'CLOTH', 'FLESH'),
	('UNIT_BAZOOKA',			'ART_DEF_UNIT_BAZOOKA_INFANTRY',	'ART_DEF_UNIT_MEMBER_BAZOOKA_INFANTRY',	3, '0.50',	'BazookaLing.fxsxml',	'CLOTH', 'FLESH'),
	('UNIT_COMPOSITE_BOWMAN',	'ART_DEF_UNIT_COMPOSITE_BOWMAN','ART_DEF_UNIT_MEMBER_COMPOSITE_BOWMAN',12, '0.14',	'CompBowLing.fxsxml',	'CLOTH', 'FLESH'),
	('UNIT_CROSSBOWMAN',		'ART_DEF_UNIT_CROSSBOWMAN',		'ART_DEF_UNIT_MEMBER_CROSSBOWMAN',		12, '0.14',	'CrossBowLing.fxsxml',	'CLOTH', 'FLESH'),
	('UNIT_ENGINEER',			'ART_DEF_UNIT_ENGINEER',		'ART_DEF_UNIT_MEMBER_ENGINEER',			1, '0.50',	'EngineerLing.fxsxml',	'CLOTH', 'FLESH'),
	('UNIT_MERCHANT',			'ART_DEF_UNIT_MERCHANT',		'ART_DEF_UNIT_MEMBER_MERCHANT',			1, '0.50',	'MerchantLing.fxsxml',	'CLOTH', 'FLESH'),
	('UNIT_MISSIONARY',			'ART_DEF_UNIT_MISSIONARY',		'ART_DEF_UNIT_MEMBER_MISSIONARY',		3, '0.50',	'MissionaryLing.fxsxml','CLOTH', 'FLESH'),
	('UNIT_INQUISITOR',			'ART_DEF_UNIT_INQUISITOR',		'ART_DEF_UNIT_MEMBER_INQUISITOR',		3, '0.50',	'InquisitorLing.fxsxml','CLOTH', 'FLESH'),
	('UNIT_LONGSWORDSMAN',		'ART_DEF_UNIT_LONGSWORDSMAN',	'ART_DEF_UNIT_MEMBER_LONGSWORDSMAN',	12, '0.50',	'LongswordLing.fxsxml', 'ARMOR', 'ARMOR'),
	('UNIT_PIKEMAN',			'ART_DEF_UNIT_PIKEMAN',			'ART_DEF_UNIT_MEMBER_PIKEMAN',			12, '0.50',	'PikeLing.fxsxml',		'ARMOR', 'ARMOR'),
	('UNIT_PROPHET',			'ART_DEF_UNIT_GREAT_PROPHET',	'ART_DEF_UNIT_MEMBER_GREAT_PROPHET',	1, '0.50',	'MissionaryLing.fxsxml','CLOTH', 'FLESH'),
	('UNIT_SCIENTIST',			'ART_DEF_UNIT_SCIENTIST',		'ART_DEF_UNIT_MEMBER_SCIENTIST',		1, '0.50',	'ScientistLing.fxsxml', 'CLOTH', 'FLESH'),
	('UNIT_SCOUT',				'ART_DEF_UNIT_SCOUT',			'ART_DEF_UNIT_MEMBER_SCOUT',			6, '0.50',	'ScoutLing.fxsxml',		'CLOTH', 'FLESH'),
	('UNIT_SETTLER',			'ART_DEF_UNIT__SETTLER',		'ART_DEF_UNIT_MEMBER_EUROFEMALE18',		1, '0.50',	'SettLing1.fxsxml',		'CLOTH', 'FLESH'),
	('UNIT_SETTLER',			'ART_DEF_UNIT__SETTLER',		'ART_DEF_UNIT_MEMBER_EUROFEMALE25',		1, '0.50',	'SettLing2.fxsxml',		'CLOTH', 'FLESH'),
	('UNIT_SETTLER',			'ART_DEF_UNIT__SETTLER',		'ART_DEF_UNIT_MEMBER_EUROFEMALE35',		1, '0.50',	'SettLing3.fxsxml',		'CLOTH', 'FLESH'),
	('UNIT_SPEARMAN',			'ART_DEF_UNIT_SPEARMAN',		'ART_DEF_UNIT_MEMBER_SPEARMAN',			12, '0.50',	'SpearLing.fxsxml',		'CLOTH', 'FLESH'),
	('UNIT_SWORDSMAN',			'ART_DEF_UNIT_SWORDSMAN',		'ART_DEF_UNIT_MEMBER_SWORDSMAN',		12, '0.50',	'SwordLing.fxsxml',		'ARMOR', 'ARMOR'),
	('UNIT_WARRIOR',			'ART_DEF_UNIT__WARRIOR',		'ART_DEF_UNIT_MEMBER_WARRIOR',			12, '0.50',	'WarriorLing.fxsxml',	'CLOTH', 'FLESH'),
	('UNIT_WORKER',				'ART_DEF_UNIT__WORKER',			'ART_DEF_UNIT_MEMBER_WORKER',			8, '0.50',	'WorkerLing.fxsxml',	'CLOTH', 'FLESH');